version: 2.1

references:
  container_config: &container_config
    docker:
      - image: circleci/node:10
    working_directory: ~/repo

  workspace_root: &workspace_root /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v1-repo-{{ .Branch }}-{{ .Revision }}
        - v1-repo-{{ .Branch }}
        - v1-repo

  npm_cache_key: &npm_cache_key v1-dependency-npm-{{ checksum "package-lock.json" }}
  npm_backup_cache_key: &npm_backup_cache_key v1-dependency-npm

  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - *npm_cache_key
        - *npm_backup_cache_key

jobs:
  checkout_code:
    <<: *container_config
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/repo

  install_dependencies:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_node_modules
      - run: npm install
      - save_cache:
          key: *npm_cache_key
          paths:
            - ~/repo/node_modules

  lint:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_node_modules
      - run: npm run eslint-check

  test:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_node_modules
      - run: npm run test

  build:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_node_modules
      - run: npm run build
      - store_artifacts:
          path: build
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - build

  stage:
    <<: *container_config
    steps:
      - *attach_workspace
      - run:
          name: Restore build assets from workspace
          command: |
            rm -r build
            mv /tmp/workspace/build build
      - run: echo "Placeholder for deploy to staging"

  deploy:
    <<: *container_config
    steps:
      - *attach_workspace
      - run:
          name: Restore build assets from workspace
          command: |
            rm -r build
            mv /tmp/workspace/build build
      - run: echo "Placeholder for deploy to prod"

workflows:
  version: 2
  lint_test_build_stage_deploy:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - lint:
          requires:
            - install_dependencies
      - test:
          requires:
            - install_dependencies
      - build:
          requires:
            - lint
            - test
      - stage:
          requires:
            - build
      - deploy:
          requires:
            - build
